name: Build
on:
  push:
    branches:
      - main
jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements-ci.txt

      - name: Run flake8
        run: |
          flake8 src/app.py
      - name: Run bandit
        run: |
          bandit --check src/ --severity-level high --recursive
  build:
    needs: checkcode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: joffreydupire
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: joffreydupire/ynovvotingapp:latest
